language: php
php:
- 5.5
- 5.6
- 7.0
- hhvm
- nightly
matrix:
  allow_failures:
  - php: nightly
sudo: false
before_script:
- travis_retry composer self-update 1.0.0-beta1
- travis_retry composer install --prefer-source --no-interaction
script:
- composer test
- composer cs
deploy:
  provider: heroku
  buildpack: https://github.com/view-components/heroku-buildpack-php
  api_key:
    secure: ABXiZKDiqKCQADPGcdn4OV5jwiTDrTTWyBjQ7/GZmSjRtleh7nY15hKuqkvGWldrJNQhrWMWVIDPCJRTtZqQuYNIgEsL9xe6kQjpFfKBoB/wUfqGPwyhOUZgdvLwSnhZUz7TG5kiqN6D8gDXBYutLCP0NLvUwcs7kqX/BUFF4hQ=
  app: view-components
  on:
    repo: view-components/view-components
  skip_cleanup: true
